//! TypeScript code generation for the desktop (`desktop/shared-types`).

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use crate::registry::{MethodDesc, CLIENT_REQUESTS, SERVER_NOTIFICATIONS, SERVER_REQUESTS};

/// Export every protocol type plus `methods.ts` and `index.ts` into `out_dir`.
/// The directory is cleared first so removed types disappear.
pub fn generate_ts(out_dir: &Path) -> anyhow_lite::Result<()> {
    if out_dir.exists() {
        std::fs::remove_dir_all(out_dir)?;
    }
    std::fs::create_dir_all(out_dir)?;

    for m in CLIENT_REQUESTS.iter().chain(SERVER_NOTIFICATIONS).chain(SERVER_REQUESTS) {
        (m.export)(out_dir).map_err(|e| anyhow_lite::Error(format!("{}: {e}", m.method)))?;
    }
    // Types not reachable from a method but used by the UI.
    use ts_rs::TS;
    crate::config_types::ConfigToml::export_all_to(out_dir).map_err(err)?;
    crate::jsonrpc::JsonRpcRequest::export_all_to(out_dir).map_err(err)?;
    crate::jsonrpc::JsonRpcResponse::export_all_to(out_dir).map_err(err)?;
    crate::jsonrpc::JsonRpcNotification::export_all_to(out_dir).map_err(err)?;
    crate::items::ItemDelta::export_all_to(out_dir).map_err(err)?;
    crate::common::ModelRole::export_all_to(out_dir).map_err(err)?;

    // Post-process: nullable fields become optional (`x?: T | null`), matching
    // serde's tolerance for missing Option fields.
    let files = list_ts(out_dir);
    for f in &files {
        let src = std::fs::read_to_string(f)?;
        let fixed = make_nullable_optional(&src);
        if fixed != src {
            std::fs::write(f, fixed)?;
        }
    }

    // index.ts
    let mut index = String::from("// GENERATED by `odex-engine generate-ts`. Do not edit.\n");
    let mut rels: Vec<String> = files
        .iter()
        .map(|f| {
            let rel = f.strip_prefix(out_dir).unwrap().with_extension("");
            rel.to_string_lossy().replace('\\', "/")
        })
        .collect();
    rels.sort();
    for rel in &rels {
        let _ = writeln!(index, "export * from \"./{rel}\";");
    }
    index.push_str("export * from \"./methods\";\n");
    std::fs::write(out_dir.join("index.ts"), index)?;

    // methods.ts
    let mut out = String::from("// GENERATED by `odex-engine generate-ts`. Do not edit.\n");
    let mut imports: Vec<String> = Vec::new();
    let mut collect = |t: String| {
        if !imports.contains(&t) {
            imports.push(t);
        }
    };
    for m in CLIENT_REQUESTS.iter().chain(SERVER_NOTIFICATIONS).chain(SERVER_REQUESTS) {
        collect((m.params)());
        if let Some(r) = m.result {
            collect(r());
        }
    }
    imports.sort();
    for t in &imports {
        let path = rels
            .iter()
            .find(|r| r.rsplit('/').next() == Some(t.as_str()))
            .cloned()
            .unwrap_or_else(|| t.clone());
        let _ = writeln!(out, "import type {{ {t} }} from \"./{path}\";");
    }
    let _ = writeln!(out, "\nexport const PROTOCOL_VERSION = \"{}\";\n", crate::PROTOCOL_VERSION);
    write_request_map(&mut out, "ClientRequestMap", CLIENT_REQUESTS);
    write_notification_map(&mut out, "ServerNotificationMap", SERVER_NOTIFICATIONS);
    write_request_map(&mut out, "ServerRequestMap", SERVER_REQUESTS);
    out.push_str("export type ClientMethod = keyof ClientRequestMap;\n");
    out.push_str("export type ServerNotificationMethod = keyof ServerNotificationMap;\n");
    out.push_str("export type ServerRequestMethod = keyof ServerRequestMap;\n");
    out.push_str("export type ParamsOf<M extends ClientMethod> = ClientRequestMap[M][\"params\"];\n");
    out.push_str("export type ResultOf<M extends ClientMethod> = ClientRequestMap[M][\"result\"];\n");
    std::fs::write(out_dir.join("methods.ts"), out)?;
    Ok(())
}

fn err(e: ts_rs::ExportError) -> anyhow_lite::Error {
    anyhow_lite::Error(e.to_string())
}

fn write_request_map(out: &mut String, name: &str, table: &[MethodDesc]) {
    let _ = writeln!(out, "export interface {name} {{");
    for m in table {
        let _ = writeln!(
            out,
            "  \"{}\": {{ params: {}; result: {} }};",
            m.method,
            (m.params)(),
            m.result.map(|r| r()).unwrap_or_else(|| "void".into())
        );
    }
    out.push_str("}\n\n");
}

fn write_notification_map(out: &mut String, name: &str, table: &[MethodDesc]) {
    let _ = writeln!(out, "export interface {name} {{");
    for m in table {
        let _ = writeln!(out, "  \"{}\": {};", m.method, (m.params)());
    }
    out.push_str("}\n\n");
}

fn list_ts(dir: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let mut stack = vec![dir.to_path_buf()];
    while let Some(d) = stack.pop() {
        if let Ok(rd) = std::fs::read_dir(&d) {
            for e in rd.flatten() {
                let p = e.path();
                if p.is_dir() {
                    stack.push(p);
                } else if p.extension().map(|x| x == "ts").unwrap_or(false) {
                    out.push(p);
                }
            }
        }
    }
    out.sort();
    out
}

/// Rewrites `name: T | null` fields inside object types to `name?: T | null`.
/// Works on ts-rs output: fields are `ident: type` separated by `,` at depth 0
/// of their enclosing `{ }`.
pub fn make_nullable_optional(src: &str) -> String {
    let chars: Vec<char> = src.chars().collect();
    let mut out = String::with_capacity(src.len() + 64);
    let mut i = 0;
    // Stack of bracket kinds; we only treat `{` contexts as objects.
    let mut stack: Vec<char> = Vec::new();
    let mut in_str: Option<char> = None;
    while i < chars.len() {
        let c = chars[i];
        if let Some(q) = in_str {
            out.push(c);
            if c == '\\' && i + 1 < chars.len() {
                out.push(chars[i + 1]);
                i += 2;
                continue;
            }
            if c == q {
                in_str = None;
            }
            i += 1;
            continue;
        }
        if c == '/' && i + 1 < chars.len() && (chars[i + 1] == '*' || chars[i + 1] == '/') {
            // copy comments verbatim
            let block = chars[i + 1] == '*';
            out.push(chars[i]);
            out.push(chars[i + 1]);
            i += 2;
            while i < chars.len() {
                out.push(chars[i]);
                if block && chars[i] == '/' && chars[i - 1] == '*' {
                    i += 1;
                    break;
                }
                if !block && chars[i] == '\n' {
                    i += 1;
                    break;
                }
                i += 1;
            }
            continue;
        }
        match c {
            '"' | '\'' => {
                in_str = Some(c);
                out.push(c);
                i += 1;
            }
            '{' | '<' | '(' | '[' => {
                stack.push(c);
                out.push(c);
                i += 1;
            }
            '}' | '>' | ')' | ']' => {
                // `=>` arrows are not brackets
                if c == '>' && i > 0 && chars[i - 1] == '=' {
                    out.push(c);
                    i += 1;
                    continue;
                }
                stack.pop();
                out.push(c);
                i += 1;
            }
            _ if stack.last() == Some(&'{') && (c.is_alphabetic() || c == '_' || c == '$') && is_field_start(&chars, i) => {
                // read identifier
                let start = i;
                while i < chars.len() && (chars[i].is_alphanumeric() || chars[i] == '_' || chars[i] == '$') {
                    i += 1;
                }
                let ident: String = chars[start..i].iter().collect();
                if i < chars.len() && chars[i] == ':' {
                    // find the end of the type at depth 0
                    let ty_start = i + 1;
                    let mut j = ty_start;
                    let mut depth = 0i32;
                    let mut q: Option<char> = None;
                    while j < chars.len() {
                        let d = chars[j];
                        if let Some(qq) = q {
                            if d == qq {
                                q = None;
                            }
                            j += 1;
                            continue;
                        }
                        match d {
                            '"' | '\'' => q = Some(d),
                            '{' | '<' | '(' | '[' => depth += 1,
                            '>' if j > 0 && chars[j - 1] == '=' => {}
                            '}' | '>' | ')' | ']' => {
                                if depth == 0 {
                                    break;
                                }
                                depth -= 1;
                            }
                            ',' | ';' if depth == 0 => break,
                            _ => {}
                        }
                        j += 1;
                    }
                    let ty: String = chars[ty_start..j].iter().collect();
                    out.push_str(&ident);
                    if ty.trim_end().ends_with("| null") {
                        out.push('?');
                    }
                    out.push(':');
                    i = ty_start;
                } else {
                    out.push_str(&ident);
                }
            }
            _ => {
                out.push(c);
                i += 1;
            }
        }
    }
    out
}

fn is_field_start(chars: &[char], i: usize) -> bool {
    // previous non-space, non-comment char must be `{` or `,`
    let mut k = i;
    while k > 0 {
        k -= 1;
        let p = chars[k];
        if p.is_whitespace() {
            continue;
        }
        // skip a `/* ... */` block comment backwards
        if p == '/' && k > 0 && chars[k - 1] == '*' {
            k -= 1;
            while k > 1 && !(chars[k - 1] == '/' && chars[k] == '*') {
                k -= 1;
            }
            k = k.saturating_sub(1);
            continue;
        }
        return p == '{' || p == ',';
    }
    false
}

/// Tiny error type so the protocol crate stays dependency-light.
pub mod anyhow_lite {
    #[derive(Debug)]
    pub struct Error(pub String);
    impl std::fmt::Display for Error {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(&self.0)
        }
    }
    impl std::error::Error for Error {}
    impl From<std::io::Error> for Error {
        fn from(e: std::io::Error) -> Self {
            Error(e.to_string())
        }
    }
    pub type Result<T> = std::result::Result<T, Error>;
}

#[cfg(test)]
mod tests {
    use super::make_nullable_optional;

    #[test]
    fn nullable_fields_become_optional() {
        let src = "export type A = { a: string, b: string | null, c: Array<{ d: number | null }>, e: { [key in string]?: string } | null, };";
        let out = make_nullable_optional(src);
        assert_eq!(
            out,
            "export type A = { a: string, b?: string | null, c: Array<{ d?: number | null }>, e?: { [key in string]?: string } | null, };"
        );
    }

    #[test]
    fn doc_commented_fields() {
        let src = "export type A = { a: string, \n/**\n * doc, with comma\n */\nb: string | null, };";
        let out = make_nullable_optional(src);
        assert!(out.contains("b?: string | null"), "{out}");
    }

    #[test]
    fn tagged_unions_untouched() {
        let src = r#"export type U = { "type": "text", text: string, } | { "type": "img", url: string | null, };"#;
        let out = make_nullable_optional(src);
        assert!(out.contains("url?: string | null"));
        assert!(out.contains("text: string"));
    }
}
